**INSTITUTO TECNOLOGICO Y DE ESTUDIOS SUPERIORES DE MONTERREY**

**CAMPUS PUEBLA**

**ANALITICA DE DATOS Y HERRAMIENTAS DE INTELIGENCIA ARTIFICIAL II**

**GRUPO: 501**

**Sebastian Contreras Hernández**

**MATRICULA: A01735880**

**PROFESOR:**

**Alfredo García Suárez**

**FECHA: 25/09/2024**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import ast

In [2]:
#Carga desde un archivo .csv desde equipo
data = pd.read_csv('listings.csv')
data.head(5)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,898633,https://www.airbnb.com/rooms/898633,20240627045222,2024-06-28,city scrape,City SkyLine View from 1 Bedroom Apt in CDMX,The LOCATION is undoubtedly THE BIG advantage ...,The hipster Roma neighborhood embodies a color...,https://a0.muscache.com/pictures/ba75b1c1-cb02...,4796027,...,4.96,4.93,4.91,NaN,f,3,2,1,0,0.41
1,35797,https://www.airbnb.com/rooms/35797,20240627045222,2024-06-27,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Mall, Interloma Park and the Lion Des...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
2,44616,https://www.airbnb.com/rooms/44616,20240627045222,2024-06-28,city scrape,CONDESA HAUS B&B,A new concept of hosting in mexico through a b...,NaN,https://a0.muscache.com/pictures/251410/ec75fe...,196253,...,4.78,4.98,4.48,NaN,f,13,4,2,0,0.42
3,913084,https://www.airbnb.com/rooms/913084,20240627045222,2024-06-28,city scrape,15 blocks from Paseo de la Reforma,NaN,"It borders the old and traditional San Rafael,...",https://a0.muscache.com/pictures/16663562/7bed...,4647293,...,4.93,4.46,4.75,NaN,t,1,1,0,0,1.19
4,67703,https://www.airbnb.com/rooms/67703,20240627045222,2024-06-28,city scrape,"2 bedroom apt. deco bldg, Condesa","Comfortably furnished, sunny, 2 bedroom apt., ...",NaN,https://a0.muscache.com/pictures/3281720/6f078...,334451,...,4.92,4.98,4.91,NaN,f,2,2,0,0,0.32

## Analisis del dataframe

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26536 entries, 0 to 26535
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            26536 non-null  int64
 1   listing_url                                   26536 non-null  object
 2   scrape_id                                     26536 non-null  int64
 3   last_scraped                                  26536 non-null  object
 4   source                                        26536 non-null  object
 5   name                                          26536 non-null  object
 6   description                                   25585 non-null  object
 7   neighborhood_overview                         16246 non-null  object
 8   picture_url                                   26536 non-null  object
 9   host_id                                       26536 non-null  int64
 10  host_url                                      26536 non-null  object
 11  host_name                                     26536 non-null  object
 12  host_since                                    26536 non-null  object
 13  host_location                                 20930 non-null  object
 14  host_about                                    15354 non-null  object
 15  host_response_time                            22339 non-null  object
 16  host_response_rate                            22339 non-null  object
 17  host_acceptance_rate                          23681 non-null  object
 18  host_is_superhost                             24993 non-null  object
 19  host_thumbnail_url                            26536 non-null  object
 20  host_picture_url                              26536 non-null  object
 21  host_neighbourhood                            13181 non-null  object
 22  host_listings_count                           26536 non-null  int64
 23  host_total_listings_count                     26536 non-null  int64
 24  host_verifications                            26536 non-null  object
 25  host_has_profile_pic                          26536 non-null  object
 26  host_identity_verified                        26536 non-null  object
 27  neighbourhood                                 16246 non-null  object
 28  neighbourhood_cleansed                        26536 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      26536 non-null  float64
 31  longitude                                     26536 non-null  float64
 32  property_type                                 26536 non-null  object
 33  room_type                                     26536 non-null  object
 34  accommodates                                  26536 non-null  int64
 35  bathrooms                                     23407 non-null  float64
 36  bathrooms_text                                26511 non-null  object
 37  bedrooms                                      25465 non-null  float64
 38  beds                                          23372 non-null  float64
 39  amenities                                     26536 non-null  object
 40  price                                         23338 non-null  object
 41  minimum_nights                                26536 non-null  int64
 42  maximum_nights                                26536 non-null  int64
 43  minimum_minimum_nights                        26536 non-null  int64
 44  maximum_minimum_nights                        26536 non-null  int64
 45  minimum_maximum_nights                        26536 non-null  int64
 46  maximum_maximum_nights                        26536 non-null  int64
 47  minimum_nights_avg_ntm                        26536 non-null  float64
 48  maximum_nights_avg_ntm                        26536 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              25500 non-null  object
 51  availability_30                               26536 non-null  int64
 52  availability_60                               26536 non-null  int64
 53  availability_90                               26536 non-null  int64
 54  availability_365                              26536 non-null  int64
 55  calendar_last_scraped                         26536 non-null  object
 56  number_of_reviews                             26536 non-null  int64
 57  number_of_reviews_ltm                         26536 non-null  int64
 58  number_of_reviews_l30d                        26536 non-null  int64
 59  first_review                                  22664 non-null  object
 60  last_review                                   22664 non-null  object
 61  review_scores_rating                          22664 non-null  float64
 62  review_scores_accuracy                        22649 non-null  float64
 63  review_scores_cleanliness                     22648 non-null  float64
 64  review_scores_checkin                         22649 non-null  float64
 65  review_scores_communication                   22649 non-null  float64
 66  review_scores_location                        22649 non-null  float64
 67  review_scores_value                           22649 non-null  float64
 68  license                                       0 non-null      float64
 69  instant_bookable                              26536 non-null  object
 70  calculated_host_listings_count                26536 non-null  int64
 71  calculated_host_listings_count_entire_homes   26536 non-null  int64
 72  calculated_host_listings_count_private_rooms  26536 non-null  int64
 73  calculated_host_listings_count_shared_rooms   26536 non-null  int64
 74  reviews_per_month                             22664 non-null  float64
dtypes: float64(18), int64(23), object(34)
memory usage: 15.2+ MB

In [4]:
pd.options.display.max_columns = 80

In [5]:
pd.options.display.max_rows = 100

In [6]:
#Identificar valores nulos por columna
valores_nulos=data.isnull().sum()
valores_nulos

id                                                  0
listing_url                                         0
scrape_id                                           0
last_scraped                                        0
source                                              0
name                                                0
description                                       951
neighborhood_overview                           10290
picture_url                                         0
host_id                                             0
host_url                                            0
host_name                                           0
host_since                                          0
host_location                                    5606
host_about                                      11182
host_response_time                               4197
host_response_rate                               4197
host_acceptance_rate                             2855
host_is_superhost                                1543
host_thumbnail_url                                  0
host_picture_url                                    0
host_neighbourhood                              13355
host_listings_count                                 0
host_total_listings_count                           0
host_verifications                                  0
host_has_profile_pic                                0
host_identity_verified                              0
neighbourhood                                   10290
neighbourhood_cleansed                              0
neighbourhood_group_cleansed                    26536
latitude                                            0
longitude                                           0
property_type                                       0
room_type                                           0
accommodates                                        0
bathrooms                                        3129
bathrooms_text                                     25
bedrooms                                         1071
beds                                             3164
amenities                                           0
price                                            3198
minimum_nights                                      0
maximum_nights                                      0
minimum_minimum_nights                              0
maximum_minimum_nights                              0
minimum_maximum_nights                              0
maximum_maximum_nights                              0
minimum_nights_avg_ntm                              0
maximum_nights_avg_ntm                              0
calendar_updated                                26536
has_availability                                 1036
availability_30                                     0
availability_60                                     0
availability_90                                     0
availability_365                                    0
calendar_last_scraped                               0
number_of_reviews                                   0
number_of_reviews_ltm                               0
number_of_reviews_l30d                              0
first_review                                     3872
last_review                                      3872
review_scores_rating                             3872
review_scores_accuracy                           3887
review_scores_cleanliness                        3888
review_scores_checkin                            3887
review_scores_communication                      3887
review_scores_location                           3887
review_scores_value                              3887
license                                         26536
instant_bookable                                    0
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
reviews_per_month                                3872
dtype: int64

In [7]:
#Identificar valores nulos por dataframe
valores_nulos=data.isnull().sum().sum()
valores_nulos

194508

## Eliminación de columnas

In [8]:
# Se eliminan las URL's de la base de datos:
data.drop(["listing_url","host_url","picture_url","host_thumbnail_url","host_picture_url","id"], axis = 1, inplace = True)
# Se eliminan las columnas con valores nulos (Del más del 80%) que tenemos en las bases del equipo
data.drop(["neighbourhood_group_cleansed","calendar_updated","license"], axis = 1, inplace = True)
data

,scrape_id,last_scraped,source,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,20240627045222,2024-06-28,city scrape,City SkyLine View from 1 Bedroom Apt in CDMX,The LOCATION is undoubtedly THE BIG advantage ...,The hipster Roma neighborhood embodies a color...,4796027,Marco,2013-01-21,"Mexico City, Mexico","I'm Marco. I am a graphic designer, but I also...",within an hour,100%,88%,t,Roma Norte,3,6,"['email', 'phone']",t,t,"Mexico City, Federal District, Mexico",Cuauhtémoc,19.420630,-99.165860,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,2.0,"[""40 inch HDTV with Amazon Prime Video, Netfli...","$1,652.00",3,48,3,3,48,48,3.0,48.0,t,0,5,23,262,2024-06-28,56,3,0,2013-03-30,2024-04-17,4.95,4.93,4.95,4.93,4.96,4.93,4.91,f,3,2,1,0,0.41
1,20240627045222,2024-06-27,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Mall, Interloma Park and the Lion Des...",153786,Dici,2010-06-28,"Mexico City, Mexico","Master in visual arts, film photography & Mark...",a few days or more,0%,NaN,f,NaN,1,1,"['email', 'phone', 'work_email']",t,t,"Mexico City, D.f., Mexico",Cuajimalpa de Morelos,19.382830,-99.271780,Entire villa,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Hot water"", ""Washer"", ""Bed linens"", ""Wifi"", ...","$3,663.00",1,7,1,1,7,7,1.0,7.0,t,28,58,88,363,2024-06-27,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
2,20240627045222,2024-06-28,city scrape,CONDESA HAUS B&B,A new concept of hosting in mexico through a b...,NaN,196253,Fernando,2010-08-09,"Mexico City, Mexico",Condesa Haus offers independent studios and ...,within an hour,100%,92%,t,Condesa,17,17,"['email', 'phone', 'work_email']",t,t,NaN,Cuauhtémoc,19.411620,-99.177940,Entire home,Entire home/apt,14,5.5,5.5 baths,5.0,8.0,"[""Wifi"", ""Coffee maker: Nespresso"", ""Host gree...","$18,000.00",1,365,1,1,365,365,1.0,365.0,t,29,59,89,364,2024-06-28,64,0,0,2011-11-09,2023-03-26,4.58,4.56,4.70,4.87,4.78,4.98,4.48,f,13,4,2,0,0.42
3,20240627045222,2024-06-28,city scrape,15 blocks from Paseo de la Reforma,NaN,"It borders the old and traditional San Rafael,...",4647293,Martina,2013-01-09,"Mexico City, Mexico",My motto in life is that everything in life ha...,within an hour,100%,96%,t,NaN,1,4,"['email', 'phone']",t,t,"Mexico City, Federal District, Mexico",Miguel Hidalgo,19.439560,-99.172630,Entire serviced apartment,Entire home/apt,4,1.0,1 bath,2.0,3.0,"[""Wifi"", ""Host greets you"", ""Coffee maker"", ""S...",$814.00,2,1125,2,2,1125,1125,2.0,1125.0,t,3,22,26,236,2024-06-28,161,6,0,2013-05-16,2024-05-21,4.75,4.83,4.72,4.84,4.93,4.46,4.75,t,1,1,0,0,1.19
4,20240627045222,2024-06-28,city scrape,"2 bedroom apt. deco bldg, Condesa","Comfortably furnished, sunny, 2 bedroom apt., ...",NaN,334451,Nicholas,2011-01-04,"Mexico City, Mexico","I am a journalist writing about food, (book an...",within a day,89%,62%,t,Hipódromo,3,4,"['email', 'phone']",t,t,NaN,Cuauhtémoc,19.411520,-99.168570,Entire rental unit,Entire home/apt,4,1.0,1 bath,2.0,2.0,"[""Wifi"", ""Coffee maker"", ""Sound system"", ""Clot...","$1,923.00",2,30,2,2,30,30,2.0,30.0,t,26,56,86,361,2024-06-28,49,4,0,2011-11-17,2024-05-05,4.90,4.81,4.75,4.94,4.92,4.98,4.91,f,2,2,0,0,0.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26531,20240627045222,2024-06-28,city scrape,¡Crystal! - 7BR Fantastic! In heart of Roma,Located in the vibrant neighborhood of Roma Su...,NaN,19255745,Elvy,2014-07-31,"Mexico City, Mexico","Soy Publicista, tengo una empresa de medios ex...",within an hour,100%,100%,t,Chapultepec Morales,13,15,"['email', 'phone']",t,t,NaN,Cuauhtémoc,19.404546,-99.168252,Entire home,Entire home/apt,16,4.5,4.5 baths,7.0,7.0,"[""Wifi"", ""Smoke alarm"", ""Essentials"", ""Room-da...","$7,850.00",2,365,2,2,365,365,2.0,365.0,t,30,60,90,365,2024-06-28,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,8,8,0,0,NaN
26532,20240627045222,2024-06-28,city scrape,Iconic Suite | Terrace | View !,"Welcome to Icon Cibles, a newly built modern s...",NaN,7681206,Nicolas,2013-07-23,"Mexico City, Mexico",My name is Nico and I will be the lucky one to...,within an hour,97%,91%,f,Gardenia Terrace - Arther Terrace,33,51,"['email', 'phone']",t,t,NaN,Cuauhtémoc,19.420567,-99.166263,Entire rental unit,Entire home/apt,3,1.0,1 bath,1.0,2.0,"[""Wifi"", ""Outdoor furniture"", ""Portable fans"",...","$1,478.00",1,365,1,1,365,365,1.0,365.0,t,28,58,88,363,2024-06-28,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,11,11,0,0,NaN
26533,20240627045222,2024-06-28,city scrape,Acogedor y moderno depa en la Condesa,Enjoy the warmth and tranquility provided by t...,NaN,50951150,Sandra,2015-12-09,"Cocoyoc, Mexico",Me gusta viajar sintiendo que no he salido de ...,within an hour,100%,100%,NaN,Residencial Casco Antiguo,12,15,"['email', 'phone', 'work_email']",t,t,NaN,Cuauhtémoc,19.408648,-99.170992,Entire rental unit,Entire home/apt,3,1.0,1 bath,1.0,1.0,"[""Wifi"", ""Smoke alarm"", ""Wine glasses"", ""Essen...",$936.00,2,365,2,2,365,365,2.0,365.0,t,28,58,88,363,2024-06-28,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
26534,20240627045222,2024-06-28,city scrape,Estudio con amplia terraza,Private studio on the top floor of an old hous...,NaN,147254250,Salomon,2017-08-22,"Mexico City, Mexico",I´m a filmaker based in Mexico City. I like to...,within an hour,100%,100%,t,Roma Norte,3,3,"['email', 'phone']",t,t,NaN,Cuauhtémoc,19.412367,-99.166447,Entire home,Entire home/apt,4,1.5,1.5 baths,1.0,2.0,"[""Washer"", ""Wifi"", ""Exterior security cameras ...",$768.00,1,365,1,1,365,365,1.0,365.0,t,14,44,74,254,2024-06-28,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,3,3,0,0,NaN
26535,20240627045222,2024-06-28,city scrape,"Apt with Reforma View, Pool and Jacuzzi",Discover a unique accommodation experience in ...,"With a strategic location, our apartment place...",67472234,HostPal,2016-04-16,"Mexico City, Mexico",NaN,within an hour,100%,87%,t,NaN,159,256,"['email', 'phone']",t,t,"Mexico City, Ciudad de México, Mexico",Cuauhtémoc,19.433861,-99.154975,Entire rental unit,Entire home/apt,4,1.0,1 bath,2.0,2.0,"["". shampoo"", ""Wifi"", ""Outdoor furniture"", ""Po...","$1,302.00",1,45,1,4,45,45,2.1,45.0,t,17,47,77,352,2024-06-28,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,35,15,20,0,NaN

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26536 entries, 0 to 26535
Data columns (total 66 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   scrape_id                                     26536 non-null  int64
 1   last_scraped                                  26536 non-null  object
 2   source                                        26536 non-null  object
 3   name                                          26536 non-null  object
 4   description                                   25585 non-null  object
 5   neighborhood_overview                         16246 non-null  object
 6   host_id                                       26536 non-null  int64
 7   host_name                                     26536 non-null  object
 8   host_since                                    26536 non-null  object
 9   host_location                                 20930 non-null  object
 10  host_about                                    15354 non-null  object
 11  host_response_time                            22339 non-null  object
 12  host_response_rate                            22339 non-null  object
 13  host_acceptance_rate                          23681 non-null  object
 14  host_is_superhost                             24993 non-null  object
 15  host_neighbourhood                            13181 non-null  object
 16  host_listings_count                           26536 non-null  int64
 17  host_total_listings_count                     26536 non-null  int64
 18  host_verifications                            26536 non-null  object
 19  host_has_profile_pic                          26536 non-null  object
 20  host_identity_verified                        26536 non-null  object
 21  neighbourhood                                 16246 non-null  object
 22  neighbourhood_cleansed                        26536 non-null  object
 23  latitude                                      26536 non-null  float64
 24  longitude                                     26536 non-null  float64
 25  property_type                                 26536 non-null  object
 26  room_type                                     26536 non-null  object
 27  accommodates                                  26536 non-null  int64
 28  bathrooms                                     23407 non-null  float64
 29  bathrooms_text                                26511 non-null  object
 30  bedrooms                                      25465 non-null  float64
 31  beds                                          23372 non-null  float64
 32  amenities                                     26536 non-null  object
 33  price                                         23338 non-null  object
 34  minimum_nights                                26536 non-null  int64
 35  maximum_nights                                26536 non-null  int64
 36  minimum_minimum_nights                        26536 non-null  int64
 37  maximum_minimum_nights                        26536 non-null  int64
 38  minimum_maximum_nights                        26536 non-null  int64
 39  maximum_maximum_nights                        26536 non-null  int64
 40  minimum_nights_avg_ntm                        26536 non-null  float64
 41  maximum_nights_avg_ntm                        26536 non-null  float64
 42  has_availability                              25500 non-null  object
 43  availability_30                               26536 non-null  int64
 44  availability_60                               26536 non-null  int64
 45  availability_90                               26536 non-null  int64
 46  availability_365                              26536 non-null  int64
 47  calendar_last_scraped                         26536 non-null  object
 48  number_of_reviews                             26536 non-null  int64
 49  number_of_reviews_ltm                         26536 non-null  int64
 50  number_of_reviews_l30d                        26536 non-null  int64
 51  first_review                                  22664 non-null  object
 52  last_review                                   22664 non-null  object
 53  review_scores_rating                          22664 non-null  float64
 54  review_scores_accuracy                        22649 non-null  float64
 55  review_scores_cleanliness                     22648 non-null  float64
 56  review_scores_checkin                         22649 non-null  float64
 57  review_scores_communication                   22649 non-null  float64
 58  review_scores_location                        22649 non-null  float64
 59  review_scores_value                           22649 non-null  float64
 60  instant_bookable                              26536 non-null  object
 61  calculated_host_listings_count                26536 non-null  int64
 62  calculated_host_listings_count_entire_homes   26536 non-null  int64
 63  calculated_host_listings_count_private_rooms  26536 non-null  int64
 64  calculated_host_listings_count_shared_rooms   26536 non-null  int64
 65  reviews_per_month                             22664 non-null  float64
dtypes: float64(15), int64(22), object(29)
memory usage: 13.4+ MB

## Limpieza de DataFrame

In [10]:
#Realizamos una copia del dataframe
data2=data.copy()

In [11]:
# Se eliminan los símbolos que hacen que la columna de precio sea de tipo objeto

data2['host_response_rate'] = data2['host_response_rate'].str.replace('%', '')
data2['host_acceptance_rate'] = data2['host_acceptance_rate'].str.replace('%', '')
data2['host_is_superhost'] = data2['host_is_superhost'].str.replace('f', '0')
data2['host_is_superhost'] = data2['host_is_superhost'].str.replace('t', '1')
data2['host_has_profile_pic'] = data2['host_has_profile_pic'].str.replace('f', '0')
data2['host_has_profile_pic'] = data2['host_has_profile_pic'].str.replace('t', '1')
data2['host_identity_verified'] = data2['host_identity_verified'].str.replace('f', '0')
data2['host_identity_verified'] = data2['host_identity_verified'].str.replace('t', '1')
data2['instant_bookable'] = data2['instant_bookable'].str.replace('f', '0')
data2['instant_bookable'] = data2['instant_bookable'].str.replace('t', '1')

# Se convierte a numérico

data2['host_response_rate'] = pd.to_numeric(data2['host_response_rate'], errors='coerce')
data2['host_acceptance_rate'] = pd.to_numeric(data2['host_acceptance_rate'], errors='coerce')
data2['host_is_superhost'] = pd.to_numeric(data2['host_is_superhost'], errors='coerce')
data2['host_has_profile_pic'] = pd.to_numeric(data2['host_has_profile_pic'], errors='coerce')
data2['host_identity_verified'] = pd.to_numeric(data2['host_identity_verified'], errors='coerce')
data2['instant_bookable'] = pd.to_numeric(data2['instant_bookable'], errors='coerce')
data2['price'] = data2['price'].str.replace(r'[\$,]', '', regex=True).astype(float)

In [12]:
# Se extrae el año de la última review y la del año donde inició el host de cada lugar
data2["last_review"]
data2["host_since"]
# Usamos una expresión regular para extraer el año
data2['last_review'] = data2['last_review'].str.extract(r'(\d{4})')
data2['last_review'] = pd.to_numeric(data2['last_review'], errors='coerce')
data2['host_since'] = data2['host_since'].str.extract(r'(\d{4})')
data2['host_since'] = pd.to_numeric(data2['host_since'], errors='coerce')
# Se agrega una nueva columna
data2['host_years'] = data2["last_review"].max() - data2['host_since']

In [13]:
# Borramos las cualitativas
data2.drop(["description","neighborhood_overview","host_about","host_neighbourhood","name","neighbourhood","host_location","first_review","has_availability"], axis = 1, inplace = True)
# Borramos las cuantitativas
data2.drop(["scrape_id","minimum_nights","maximum_nights","minimum_minimum_nights","minimum_maximum_nights", "maximum_minimum_nights", "maximum_maximum_nights","availability_60", "availability_90", "calculated_host_listings_count_entire_homes", "calculated_host_listings_count_private_rooms", "calculated_host_listings_count_shared_rooms","last_review"], axis = 1, inplace = True)

In [14]:
# Dividimos por valores cuantitativos y cualitativos
cuantis = data2.select_dtypes(np.number)
cualis = data2.select_dtypes(include=['object'])

## Sustitución valores nulos

In [15]:
# Identificamos valores cualitativos nulos
cualis.isnull().sum()

last_scraped                 0
source                       0
host_name                    0
host_response_time        4197
host_verifications           0
neighbourhood_cleansed       0
property_type                0
room_type                    0
bathrooms_text              25
amenities                    0
calendar_last_scraped        0
dtype: int64

In [16]:
#Creamos una copia para manipulación
cualis_limpia = cualis.copy()

In [17]:
# Se sutituyen los valores nulos por la moda dadas las categorías y distribución de los datos
moda = cualis_limpia["host_response_time"].value_counts().index[0]
cualis_limpia["host_response_time"] = cualis_limpia["host_response_time"].fillna(moda)

In [18]:
# Al contar con solo 25 datos nulos de igual manera se sustituirá con la moda
moda1 = cualis_limpia["bathrooms_text"].value_counts().index[0]
cualis_limpia["bathrooms_text"] = cualis_limpia["bathrooms_text"].fillna(moda)

In [19]:
# Corroboramos que no tengamos valores nulos
cualis_limpia.isnull().sum().sum()

0

In [20]:
# Generamos una copia para la limpieza de cuantitativos
cuantis_limpia = cuantis.copy()

In [21]:
# Identificar valores cualitativos nulos
cuantis_limpia.isnull().sum()

host_id                              0
host_since                           0
host_response_rate                4197
host_acceptance_rate              2855
host_is_superhost                 1543
host_listings_count                  0
host_total_listings_count            0
host_has_profile_pic                 0
host_identity_verified               0
latitude                             0
longitude                            0
accommodates                         0
bathrooms                         3129
bedrooms                          1071
beds                              3164
price                             3198
minimum_nights_avg_ntm               0
maximum_nights_avg_ntm               0
availability_30                      0
availability_365                     0
number_of_reviews                    0
number_of_reviews_ltm                0
number_of_reviews_l30d               0
review_scores_rating              3872
review_scores_accuracy            3887
review_scores_cleanliness         3888
review_scores_checkin             3887
review_scores_communication       3887
review_scores_location            3887
review_scores_value               3887
instant_bookable                     0
calculated_host_listings_count       0
reviews_per_month                 3872
host_years                           0
dtype: int64

In [22]:
cuantis[["host_response_rate","host_acceptance_rate"]].head(5)
# Dado que presentan porcentajes se sustituye valores nulos con la media
cuantis_limpia["host_response_rate"] = cuantis_limpia["host_response_rate"].fillna(round(cuantis["host_response_rate"].mean(),1))
cuantis_limpia["host_acceptance_rate"] = cuantis_limpia["host_acceptance_rate"].fillna(round(cuantis["host_acceptance_rate"].mean(),1))

In [23]:
cuantis["host_is_superhost"].value_counts()
# Reemplazaremos por un nuevo valor
cuantis_limpia["host_is_superhost"] = cuantis_limpia["host_is_superhost"].fillna(2)

In [24]:
# Para los baños, habitaciones y camas se sustituirán valores nulos por la mediana para no afectar la distribución
cuantis_limpia["bathrooms"] = cuantis_limpia["bathrooms"].fillna(int(round(cuantis["bathrooms"].median(), 0)))
cuantis_limpia["bedrooms"] = cuantis_limpia["bedrooms"].fillna(int(round(cuantis["bedrooms"].median(), 0)))
cuantis_limpia["beds"] = cuantis_limpia["beds"].fillna(int(round(cuantis["beds"].median(), 0)))

In [25]:
# Para la columna de "precio" se sustituirán los valores nulos por la mediana para no afectar la distribución
cuantis_limpia["price"] = cuantis_limpia["price"].fillna(round(cuantis["price"].median(), 0))

In [26]:
# Columnas que inician con 'review_scores', los valores son escala Likert
dfReviewScores = cuantis_limpia.loc[:, cuantis_limpia.columns.str.contains("review_scores")]
[dfReviewScores.min(), dfReviewScores.max()]

[review_scores_rating           1.0
 review_scores_accuracy         1.0
 review_scores_cleanliness      1.0
 review_scores_checkin          1.0
 review_scores_communication    1.0
 review_scores_location         1.0
 review_scores_value            1.0
 dtype: float64,
 review_scores_rating           5.0
 review_scores_accuracy         5.0
 review_scores_cleanliness      5.0
 review_scores_checkin          5.0
 review_scores_communication    5.0
 review_scores_location         5.0
 review_scores_value            5.0
 dtype: float64]

In [27]:
# Se sustituyen los valores núlos de escala Likert con la media
cuantis_limpia["review_scores_rating"] = cuantis_limpia["review_scores_rating"].fillna(round(cuantis["review_scores_rating"].mean(), 2))
cuantis_limpia["review_scores_accuracy"] = cuantis_limpia["review_scores_accuracy"].fillna(round(cuantis["review_scores_accuracy"].mean(), 2))
cuantis_limpia["review_scores_cleanliness"] = cuantis_limpia["review_scores_cleanliness"].fillna(round(cuantis["review_scores_cleanliness"].mean(), 2))
cuantis_limpia["review_scores_checkin"] = cuantis_limpia["review_scores_checkin"].fillna(round(cuantis["review_scores_checkin"].mean(), 2))
cuantis_limpia["review_scores_communication"] = cuantis_limpia["review_scores_communication"].fillna(round(cuantis["review_scores_communication"].mean(), 2))
cuantis_limpia["review_scores_location"] = cuantis_limpia["review_scores_location"].fillna(round(cuantis["review_scores_location"].mean(), 2))
cuantis_limpia["review_scores_value"] = cuantis_limpia["review_scores_value"].fillna(round(cuantis["review_scores_value"].mean(), 2))

In [28]:
# Se redondean a valor entero

cuantis_limpia["review_scores_rating"] = cuantis_limpia["review_scores_rating"].round()
cuantis_limpia["review_scores_accuracy"] = cuantis_limpia["review_scores_accuracy"].round()
cuantis_limpia["review_scores_cleanliness"] = cuantis_limpia["review_scores_cleanliness"].round()
cuantis_limpia["review_scores_checkin"] = cuantis_limpia["review_scores_checkin"].round()
cuantis_limpia["review_scores_communication"] = cuantis_limpia["review_scores_communication"].round()
cuantis_limpia["review_scores_location"] = cuantis_limpia["review_scores_location"].round()
cuantis_limpia["review_scores_value"] = cuantis_limpia["review_scores_value"].round()

In [29]:
# Se sustituyen los valores nulos de reviews_per_month por la mediana
cuantis_limpia["reviews_per_month"] = cuantis_limpia["reviews_per_month"].fillna(round(cuantis["reviews_per_month"].median(), 2))

In [30]:
# Corroboramos que no tengamos valores nulos
cuantis_limpia.isnull().sum().sum()

0

## Categorización de las variables

In [31]:
# Unimos ambas limpiezas (Valores cuantitativos y cualitativos limpios)
dfMexicoLimpio = pd.concat([cualis_limpia, cuantis_limpia], axis=1)

In [32]:
# Asignamos categorías a las columnas de tipo texto con valores numéricos usando sklearn
labels = LabelEncoder()
# Convertir la columna de texto a valores numéricos (Categorizar con números)
dfMexicoLimpio['room_type_num'] = labels.fit_transform(dfMexicoLimpio['room_type'])
dfMexicoLimpio['neighbourhood_cleansed_num'] = labels.fit_transform(dfMexicoLimpio['neighbourhood_cleansed'])
dfMexicoLimpio['host_response_time_num'] = labels.fit_transform(dfMexicoLimpio['host_response_time'])

In [33]:
# Obtenemos categorías para bathrooms_text:
dfMexicoLimpio['bathroom_text_clean'] = dfMexicoLimpio['bathrooms_text'].str.replace(r'^\d*\.?\d*\s?', '', regex=True).str.strip()
dfMexicoLimpio['bathroom_text_clean'] = dfMexicoLimpio['bathroom_text_clean'].str.replace("baths","bath")
dfMexicoLimpio['bathroom_text_clean'] = dfMexicoLimpio['bathroom_text_clean'].str.replace("shared baths","shared bath")
dfMexicoLimpio['bathroom_text_clean'].value_counts()
# Las volvemos numéricas:
dfMexicoLimpio['bathroom_text_num'] = labels.fit_transform(dfMexicoLimpio['bathroom_text_clean'])
dfMexicoLimpio['bathroom_text_num'].value_counts()

bathroom_text_num
3    19752
5     3665
4     3033
0       44
6       25
2       14
1        3
Name: count, dtype: int64

In [34]:
# Conteo para la variable "amenities" y "host_verifications"
dfMexicoLimpio['amenities_num'] = dfMexicoLimpio['amenities'].apply(ast.literal_eval)
dfMexicoLimpio["host_verifications_num"] = dfMexicoLimpio['host_verifications'].apply(ast.literal_eval)
# Crear una nueva columna que cuenta los elementos de la lista
dfMexicoLimpio['amenities_num'] = dfMexicoLimpio['amenities_num'].apply(len)
dfMexicoLimpio['host_verifications_num'] = dfMexicoLimpio['host_verifications_num'].apply(len)

In [35]:
dfMexicoLimpio

,last_scraped,source,host_name,host_response_time,host_verifications,neighbourhood_cleansed,property_type,room_type,bathrooms_text,amenities,calendar_last_scraped,host_id,host_since,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,minimum_nights_avg_ntm,maximum_nights_avg_ntm,availability_30,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,reviews_per_month,host_years,room_type_num,neighbourhood_cleansed_num,host_response_time_num,bathroom_text_clean,bathroom_text_num,amenities_num,host_verifications_num
0,2024-06-28,city scrape,Marco,within an hour,"['email', 'phone']",Cuauhtémoc,Entire rental unit,Entire home/apt,1 bath,"[""40 inch HDTV with Amazon Prime Video, Netfli...",2024-06-28,4796027,2013,100.0,88.0,1.0,3,6,1,1,19.420630,-99.165860,2,1.0,1.0,2.0,1652.0,3.0,48.0,0,262,56,3,0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,0,3,0.41,11.0,0,4,3,bath,3,56,2
1,2024-06-27,city scrape,Dici,a few days or more,"['email', 'phone', 'work_email']",Cuajimalpa de Morelos,Entire villa,Entire home/apt,1 bath,"[""Hot water"", ""Washer"", ""Bed linens"", ""Wifi"", ...",2024-06-27,153786,2010,0.0,89.8,0.0,1,1,1,1,19.382830,-99.271780,2,1.0,1.0,1.0,3663.0,1.0,7.0,28,363,0,0,0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,0,1,1.13,14.0,0,3,0,bath,3,12,3
2,2024-06-28,city scrape,Fernando,within an hour,"['email', 'phone', 'work_email']",Cuauhtémoc,Entire home,Entire home/apt,5.5 baths,"[""Wifi"", ""Coffee maker: Nespresso"", ""Host gree...",2024-06-28,196253,2010,100.0,92.0,1.0,17,17,1,1,19.411620,-99.177940,14,5.5,5.0,8.0,18000.0,1.0,365.0,29,364,64,0,0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,0,13,0.42,14.0,0,4,3,bath,3,26,3
3,2024-06-28,city scrape,Martina,within an hour,"['email', 'phone']",Miguel Hidalgo,Entire serviced apartment,Entire home/apt,1 bath,"[""Wifi"", ""Host greets you"", ""Coffee maker"", ""S...",2024-06-28,4647293,2013,100.0,96.0,1.0,1,4,1,1,19.439560,-99.172630,4,1.0,2.0,3.0,814.0,2.0,1125.0,3,236,161,6,0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,1,1,1.19,11.0,0,9,3,bath,3,36,2
4,2024-06-28,city scrape,Nicholas,within a day,"['email', 'phone']",Cuauhtémoc,Entire rental unit,Entire home/apt,1 bath,"[""Wifi"", ""Coffee maker"", ""Sound system"", ""Clot...",2024-06-28,334451,2011,89.0,62.0,1.0,3,4,1,1,19.411520,-99.168570,4,1.0,2.0,2.0,1923.0,2.0,30.0,26,361,49,4,0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,0,2,0.32,13.0,0,4,1,bath,3,21,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26531,2024-06-28,city scrape,Elvy,within an hour,"['email', 'phone']",Cuauhtémoc,Entire home,Entire home/apt,4.5 baths,"[""Wifi"", ""Smoke alarm"", ""Essentials"", ""Room-da...",2024-06-28,19255745,2014,100.0,100.0,1.0,13,15,1,1,19.404546,-99.168252,16,4.5,7.0,7.0,7850.0,2.0,365.0,30,365,0,0,0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1,8,1.13,10.0,0,4,3,bath,3,31,2
26532,2024-06-28,city scrape,Nicolas,within an hour,"['email', 'phone']",Cuauhtémoc,Entire rental unit,Entire home/apt,1 bath,"[""Wifi"", ""Outdoor furniture"", ""Portable fans"",...",2024-06-28,7681206,2013,97.0,91.0,0.0,33,51,1,1,19.420567,-99.166263,3,1.0,1.0,2.0,1478.0,1.0,365.0,28,363,0,0,0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,0,11,1.13,11.0,0,4,3,bath,3,48,2
26533,2024-06-28,city scrape,Sandra,within an hour,"['email', 'phone', 'work_email']",Cuauhtémoc,Entire rental unit,Entire home/apt,1 bath,"[""Wifi"", ""Smoke alarm"", ""Wine glasses"", ""Essen...",2024-06-28,50951150,2015,100.0,100.0,2.0,12,15,1,1,19.408648,-99.170992,3,1.0,1.0,1.0,936.0,2.0,365.0,28,363,0,0,0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,0,1,1.13,9.0,0,4,3,bath,3,39,3
26534,2024-06-28,city scrape,Salomon,within an hour,"['email', 'phone']",Cuauhtémoc,Entire home,Entire home/apt,1.5 baths,"[""Washer"", ""Wifi"", ""Exterior security cameras ...",2024-06-28,147254250,2017,100.0,100.0,1.0,3,3,1,1,19.412367,-99.166447,4,1.5,1.0,2.0,768.0,1.0,365.0,14,254,0,0,0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,0,3,1.13,7.0,0,4,3,bath,3,10,2
26535,2024-06-28,city scrape,HostPal,within an hour,"['email', 'phone']",Cuauhtémoc,Entire rental unit,Entire home/apt,1 bath,"["". shampoo"", ""Wifi"", ""Outdoor furniture"", ""Po...",2024-06-28,67472234,2016,100.0,87.0,1.0,159,256,1,1,19.433861,-99.154975,4,1.0,2.0,2.0,1302.0,2.1,45.0,17,352,0,0,0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1,35,1.13,8.0,0,4,3,bath,3,61,2

In [36]:
dfMexicoLimpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26536 entries, 0 to 26535
Data columns (total 52 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   last_scraped                    26536 non-null  object
 1   source                          26536 non-null  object
 2   host_name                       26536 non-null  object
 3   host_response_time              26536 non-null  object
 4   host_verifications              26536 non-null  object
 5   neighbourhood_cleansed          26536 non-null  object
 6   property_type                   26536 non-null  object
 7   room_type                       26536 non-null  object
 8   bathrooms_text                  26536 non-null  object
 9   amenities                       26536 non-null  object
 10  calendar_last_scraped           26536 non-null  object
 11  host_id                         26536 non-null  int64
 12  host_since                      26536 non-null  int64
 13  host_response_rate              26536 non-null  float64
 14  host_acceptance_rate            26536 non-null  float64
 15  host_is_superhost               26536 non-null  float64
 16  host_listings_count             26536 non-null  int64
 17  host_total_listings_count       26536 non-null  int64
 18  host_has_profile_pic            26536 non-null  int64
 19  host_identity_verified          26536 non-null  int64
 20  latitude                        26536 non-null  float64
 21  longitude                       26536 non-null  float64
 22  accommodates                    26536 non-null  int64
 23  bathrooms                       26536 non-null  float64
 24  bedrooms                        26536 non-null  float64
 25  beds                            26536 non-null  float64
 26  price                           26536 non-null  float64
 27  minimum_nights_avg_ntm          26536 non-null  float64
 28  maximum_nights_avg_ntm          26536 non-null  float64
 29  availability_30                 26536 non-null  int64
 30  availability_365                26536 non-null  int64
 31  number_of_reviews               26536 non-null  int64
 32  number_of_reviews_ltm           26536 non-null  int64
 33  number_of_reviews_l30d          26536 non-null  int64
 34  review_scores_rating            26536 non-null  float64
 35  review_scores_accuracy          26536 non-null  float64
 36  review_scores_cleanliness       26536 non-null  float64
 37  review_scores_checkin           26536 non-null  float64
 38  review_scores_communication     26536 non-null  float64
 39  review_scores_location          26536 non-null  float64
 40  review_scores_value             26536 non-null  float64
 41  instant_bookable                26536 non-null  int64
 42  calculated_host_listings_count  26536 non-null  int64
 43  reviews_per_month               26536 non-null  float64
 44  host_years                      26536 non-null  float64
 45  room_type_num                   26536 non-null  int64
 46  neighbourhood_cleansed_num      26536 non-null  int64
 47  host_response_time_num          26536 non-null  int64
 48  bathroom_text_clean             26536 non-null  object
 49  bathroom_text_num               26536 non-null  int64
 50  amenities_num                   26536 non-null  int64
 51  host_verifications_num          26536 non-null  int64
dtypes: float64(20), int64(20), object(12)
memory usage: 10.5+ MB

## Categorización de la columna de precio

In [37]:
# Calculamos el número total de la población "n"
n = len(dfMexicoLimpio['price'])

In [38]:
# Límites
Max = dfMexicoLimpio["price"].max()
Min = dfMexicoLimpio["price"].min()
Limites = [Min, Max]

In [39]:
# Calculamos el rango R
R = Max - Min

In [40]:
# Regla de Sturges: Calcular el número de Intervalos de Clase "ni"
ni = 1 + 3.32*np.log10(n)
ni = int(ni)

In [41]:
# Calculamos el ancho del intervalo "i"
i = R / ni

In [42]:
# Crear 13 bordes (12 intervalos)
intervalos = np.linspace(Min, Max, 13)  # Necesitamos 13 bordes para crear 12 intervalos

In [43]:
# Definir las categorías (exactamente 12 etiquetas para 12 intervalos)
categorias = ['Muy Económico', 'Básico', 'Económico', 'Estándar', 'Costo Moderado',
              'Costo Elevado', 'Premium', 'De Lujo', 'Elite', 'Exclusivo', 'Top de Mercado', 'Único']

In [44]:
# Asignar las categorías en una nueva columna
dfMexicoLimpio['priceMexCategory'] = pd.cut(x=dfMexicoLimpio['price'], bins=intervalos, labels=categorias, include_lowest=True)

In [45]:
# Verificamos
dfMexicoLimpio['priceMexCategory']

0        Muy Económico
1        Muy Económico
2        Muy Económico
3        Muy Económico
4        Muy Económico
             ...
26531    Muy Económico
26532    Muy Económico
26533    Muy Económico
26534    Muy Económico
26535    Muy Económico
Name: priceMexCategory, Length: 26536, dtype: category
Categories (12, object): ['Muy Económico' < 'Básico' < 'Económico' < 'Estándar' ... 'Elite' < 'Exclusivo' <
                          'Top de Mercado' < 'Único']

In [46]:
dfMexicoLimpio.isnull().sum().sum()

0

In [47]:
#Convertir DataFrame a CSV
dfMexicoLimpio.to_csv("Mexico_sin_nulos.csv")

In [48]:
#descargar archivo filtrado en csv
from google.colab import files


files.download("Mexico_sin_nulos.csv")