INSTITUTO TECNOLOGICO Y DE ESTUDIOS SUPERIORES DE MONTERREY

 CAMPUS PUEBLA

ANALITICA DE DATOS Y HERRAMIENTAS DE INTELIGENCIA ARTIFICIAL II

PREPARACIÓN DE LOS DATOS

ALUMNO:

Ángel Roberto González Angulo | A01735880


PROFESORES:

Alfredo García Suárez

Candy Yuridiana Alemán Muñoz

Juan Manuel Ahuactzin Larios

Rigoberto Cerino Jiménez

GRUPO:
501


FECHA DE ENTREGA:
aa/aa/aaaa

## Librerías y lectura de la base

In [193]:
# Importar las librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import ast

In [194]:
dfOttawa = pd.read_csv("listingsOttawa.csv")
dfOttawa.head(6)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,261065,https://www.airbnb.com/rooms/261065,20240621025832,2024-06-21,city scrape,Westboro Village Executive Suite,A tastefully decorated and well equipped upper...,"Westboro Village is a century-old community, a...",https://a0.muscache.com/pictures/airflow/Hosti...,1369632,...,4.94,4.96,4.90,STR-825-691,f,1,1,0,0,0.65
1,290033,https://www.airbnb.com/rooms/290033,20240621025832,2024-06-21,city scrape,Rural charm still close to the city,Close to Strathmere and other wedding venues. ...,Most folks ask about Strathmere - we are less ...,https://a0.muscache.com/pictures/3016522/1e453...,415201,...,4.83,5.00,5.00,STR-834-339,f,1,1,0,0,0.04
2,490182,https://www.airbnb.com/rooms/490182,20240621025832,2024-06-21,city scrape,Basement Studio - Old Ottawa East,NaN,"The worlds longest skating rink, a UNESCO heri...",https://a0.muscache.com/pictures/5a7e6363-5b91...,2401179,...,5.00,4.89,4.78,NaN,f,1,0,1,0,0.12
3,674799,https://www.airbnb.com/rooms/674799,20240621025832,2024-06-21,city scrape,"Private entrance apartment, 3-bdrm - up to 8 g...",GREAT for a family or a group. The apt. is low...,"Backstreet, small family oriented, peaceful, c...",https://a0.muscache.com/pictures/e97ba375-d3d1...,2058676,...,4.87,4.70,4.65,STR-827-424,f,1,1,0,0,0.57
4,682632,https://www.airbnb.com/rooms/682632,20240621025832,2024-06-21,city scrape,"Adorable 2 bdrm, Central Ottawa PD1","This an adorable property with two bedrooms, f...","This is one of the trediest, most walkable nei...",https://a0.muscache.com/pictures/3dac520b-19e2...,3201295,...,4.89,4.89,4.78,NaN,f,6,3,3,0,0.09
5,682634,https://www.airbnb.com/rooms/682634,20240621025832,2024-06-21,city scrape,Highly desirable Ottawa & Wellington Village W...,This property is located in one of the most de...,It is one of the best neighbourhoods in @Ottaw...,https://a0.muscache.com/pictures/b15917ba-a19a...,3201295,...,5.00,4.89,4.78,Exempt,t,6,3,3,0,0.08

In [195]:
# Eliminamos las URL's de la base de datos:
dfOttawa.drop(["listing_url","host_url","picture_url","host_thumbnail_url","host_picture_url","id"], axis = 1, inplace = True)
# Eliminamos las columnas con valores nulos (Del más del 80%) que tenemos en las bases del equipo también
dfOttawa.drop(["neighbourhood_group_cleansed","calendar_updated","license"], axis = 1, inplace = True)
dfOttawa

,scrape_id,last_scraped,source,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,20240621025832,2024-06-21,city scrape,Westboro Village Executive Suite,A tastefully decorated and well equipped upper...,"Westboro Village is a century-old community, a...",1369632,Glenn,2011-11-04,"Ottawa, Canada",...,4.99,4.94,4.96,4.90,f,1,1,0,0,0.65
1,20240621025832,2024-06-21,city scrape,Rural charm still close to the city,Close to Strathmere and other wedding venues. ...,Most folks ask about Strathmere - we are less ...,415201,Daniel,2011-02-28,"Ottawa, Canada",...,5.00,4.83,5.00,5.00,f,1,1,0,0,0.04
2,20240621025832,2024-06-21,city scrape,Basement Studio - Old Ottawa East,NaN,"The worlds longest skating rink, a UNESCO heri...",2401179,Ela,2012-05-17,NaN,...,5.00,5.00,4.89,4.78,f,1,0,1,0,0.12
3,20240621025832,2024-06-21,city scrape,"Private entrance apartment, 3-bdrm - up to 8 g...",GREAT for a family or a group. The apt. is low...,"Backstreet, small family oriented, peaceful, c...",2058676,William,2012-04-02,"Ottawa, Canada",...,4.84,4.87,4.70,4.65,f,1,1,0,0,0.57
4,20240621025832,2024-06-21,city scrape,"Adorable 2 bdrm, Central Ottawa PD1","This an adorable property with two bedrooms, f...","This is one of the trediest, most walkable nei...",3201295,Greg And Valerie,2012-08-08,"Ottawa, Canada",...,4.89,4.89,4.89,4.78,f,6,3,3,0,0.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2857,20240621025832,2024-06-21,city scrape,Urban Luxury Room: free parking & high speed W...,Enjoy minimalist style in this calm and cosy s...,NaN,104583371,Vivek,2016-11-21,"Ottawa, Canada",...,NaN,NaN,NaN,NaN,f,3,0,3,0,NaN
2858,20240621025832,2024-06-21,city scrape,A room for rent in a 3-bdr apt,A room for rent for in a 3-bdr fully furnishe...,NaN,348027803,Tatiana,2020-05-29,"Mississauga, Canada",...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
2859,20240621025832,2024-06-21,city scrape,Equestrian Horse Farm Retreat in Osgoode,Escape to our prestigious equestrian farm retr...,NaN,85297148,Genevieve,2016-07-22,"Ottawa, Canada",...,NaN,NaN,NaN,NaN,t,63,62,1,0,NaN
2860,20240621025832,2024-06-21,city scrape,Industrial Loft in Hintonburg!,"Welcome to Hintonburg, Ottawa's vibrant artsy ...",NaN,21218752,Shannon,2014-09-11,"Montreal, Canada",...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
2861,20240621025832,2024-06-21,city scrape,Luxury Furnished Home,Welcome to this stunning modern home in Findla...,NaN,271086550,Mitham,2019-06-24,NaN,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [196]:
dfOttawa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2862 entries, 0 to 2861
Data columns (total 66 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   scrape_id                                     2862 non-null   int64
 1   last_scraped                                  2862 non-null   object
 2   source                                        2862 non-null   object
 3   name                                          2862 non-null   object
 4   description                                   2810 non-null   object
 5   neighborhood_overview                         1424 non-null   object
 6   host_id                                       2862 non-null   int64
 7   host_name                                     2862 non-null   object
 8   host_since                                    2862 non-null   object
 9   host_location                                 2235 non-null   object
 10  host_about                                    1379 non-null   object
 11  host_response_time                            2567 non-null   object
 12  host_response_rate                            2567 non-null   object
 13  host_acceptance_rate                          2575 non-null   object
 14  host_is_superhost                             2749 non-null   object
 15  host_neighbourhood                            1234 non-null   object
 16  host_listings_count                           2862 non-null   int64
 17  host_total_listings_count                     2862 non-null   int64
 18  host_verifications                            2862 non-null   object
 19  host_has_profile_pic                          2862 non-null   object
 20  host_identity_verified                        2862 non-null   object
 21  neighbourhood                                 1424 non-null   object
 22  neighbourhood_cleansed                        2862 non-null   object
 23  latitude                                      2862 non-null   float64
 24  longitude                                     2862 non-null   float64
 25  property_type                                 2862 non-null   object
 26  room_type                                     2862 non-null   object
 27  accommodates                                  2862 non-null   int64
 28  bathrooms                                     2652 non-null   float64
 29  bathrooms_text                                2859 non-null   object
 30  bedrooms                                      2806 non-null   float64
 31  beds                                          2651 non-null   float64
 32  amenities                                     2862 non-null   object
 33  price                                         2653 non-null   object
 34  minimum_nights                                2862 non-null   int64
 35  maximum_nights                                2862 non-null   int64
 36  minimum_minimum_nights                        2862 non-null   int64
 37  maximum_minimum_nights                        2862 non-null   int64
 38  minimum_maximum_nights                        2862 non-null   int64
 39  maximum_maximum_nights                        2862 non-null   int64
 40  minimum_nights_avg_ntm                        2862 non-null   float64
 41  maximum_nights_avg_ntm                        2862 non-null   float64
 42  has_availability                              2838 non-null   object
 43  availability_30                               2862 non-null   int64
 44  availability_60                               2862 non-null   int64
 45  availability_90                               2862 non-null   int64
 46  availability_365                              2862 non-null   int64
 47  calendar_last_scraped                         2862 non-null   object
 48  number_of_reviews                             2862 non-null   int64
 49  number_of_reviews_ltm                         2862 non-null   int64
 50  number_of_reviews_l30d                        2862 non-null   int64
 51  first_review                                  2369 non-null   object
 52  last_review                                   2369 non-null   object
 53  review_scores_rating                          2369 non-null   float64
 54  review_scores_accuracy                        2366 non-null   float64
 55  review_scores_cleanliness                     2366 non-null   float64
 56  review_scores_checkin                         2366 non-null   float64
 57  review_scores_communication                   2366 non-null   float64
 58  review_scores_location                        2366 non-null   float64
 59  review_scores_value                           2366 non-null   float64
 60  instant_bookable                              2862 non-null   object
 61  calculated_host_listings_count                2862 non-null   int64
 62  calculated_host_listings_count_entire_homes   2862 non-null   int64
 63  calculated_host_listings_count_private_rooms  2862 non-null   int64
 64  calculated_host_listings_count_shared_rooms   2862 non-null   int64
 65  reviews_per_month                             2369 non-null   float64
dtypes: float64(15), int64(22), object(29)
memory usage: 1.4+ MB

### Verificar la naturaleza de los datos cualitativos

Columnas a eliminar:
- description: La columna da una descripción detallada para las listas.
- neighborhood_overview: La columna da una descripción del vecindario donde se encuentra el lugar.
- host_about: La columna da una descripción acerca del host, no se tomará en cuenta
- host_neighbourhood: Muestra el vecindario del host, es demasiado específica
- name: Demasiado específica para analizar cada caso
- neighbourhood: La columna solo menciona el texto "Neighborhood highlights"
- has_availability: En esta columna, todas son True
- host_location: La gran mayoría tienen los mismos datos (+1,500 con la misma información)

Columnas a convertir:
- host_response_rate (Está en porcentaje, convertir a numérico)
- host_acceptance_rate (Está en porcentaje, convertir a numérico)
- host_is_superhost (Convertir a columna dicotómica "0 y 1")
- host_has_profile_pic (Convertir a columna dicotómica "0 y 1")
- host_identity_verified (Convertir a columna dicotómica "0 y 1")
- neighbourhood_cleansed (Darle categorias numéricas)
- property_type (Darle categorias numéricas)
- room_type (Darle categorias numéricas)
- amenities (Contar las amenidades / Limieza exhaustiva)
- bathrooms_text (Limpieza exhaustiva)
- price (Cambiar a número)
- instant_bookable (Cambiar a variable dicotómica "0" y "1")
- first_review - Calcularemos el año de utilizando el last_review

Columnas de detalles:
- host_since (Comparar con el año de registro más reciente)
- host_verifications (Recuperar el número de verificaciones del host)

### Verificar la naturaleza de los datos cuantitativos

Columnas a eliminar:
- scrape_id: Identificador de Airbnb
- host_total_listings_count: Demasiado específico
- minimum_nights: Demasiado redundante con otras columnas
- maximum_nights: Demasiado redundante con otras columnas
- minimum_minimum_nights: Demasiado redundante con otras columnas
- minimum_maximum_nights: Demasiado redundante con otras columnas
- maximum_minimum_nights: Demasiado redundante con otras columnas
- maximum_maximum_nights: Demasiado redundante con otras columnas
- availability_60: Existen otras columnas que nos pueden ayudar a un mejor análisis
- availability_90: Existen otras columnas que nos pueden ayudar a un mejor análisis
- calculated_host_listings_count_entire_homes: Demasiado específico
- calculated_host_listings_count_private_rooms: Demasiado específico
- calculated_host_listings_count_shared_rooms: Demasiado específico

## Etapa 1

In [197]:
dfOttawa["host_since"].value_counts()

host_since
2016-07-22    64
2015-07-14    49
2015-08-16    33
2013-07-08    24
2022-02-07    23
              ..
2013-01-25     1
2018-07-18     1
2019-03-02     1
2017-05-08     1
2011-02-28     1
Name: count, Length: 1296, dtype: int64

In [198]:
# Eliminamos los símbolos que hacen que la columna de precio sea de tipo objeto
dfOttawa['host_response_rate'] = dfOttawa['host_response_rate'].str.replace('%', '')
dfOttawa['host_acceptance_rate'] = dfOttawa['host_acceptance_rate'].str.replace('%', '')
dfOttawa['host_is_superhost'] = dfOttawa['host_is_superhost'].str.replace('f', '0')
dfOttawa['host_is_superhost'] = dfOttawa['host_is_superhost'].str.replace('t', '1')
dfOttawa['host_has_profile_pic'] = dfOttawa['host_has_profile_pic'].str.replace('f', '0')
dfOttawa['host_has_profile_pic'] = dfOttawa['host_has_profile_pic'].str.replace('t', '1')
dfOttawa['host_identity_verified'] = dfOttawa['host_identity_verified'].str.replace('f', '0')
dfOttawa['host_identity_verified'] = dfOttawa['host_identity_verified'].str.replace('t', '1')
dfOttawa['instant_bookable'] = dfOttawa['instant_bookable'].str.replace('f', '0')
dfOttawa['instant_bookable'] = dfOttawa['instant_bookable'].str.replace('t', '1')
# Convertir a numérico
dfOttawa['host_response_rate'] = pd.to_numeric(dfOttawa['host_response_rate'], errors='coerce')
dfOttawa['host_acceptance_rate'] = pd.to_numeric(dfOttawa['host_acceptance_rate'], errors='coerce')
dfOttawa['host_is_superhost'] = pd.to_numeric(dfOttawa['host_is_superhost'], errors='coerce')
dfOttawa['host_has_profile_pic'] = pd.to_numeric(dfOttawa['host_has_profile_pic'], errors='coerce')
dfOttawa['host_identity_verified'] = pd.to_numeric(dfOttawa['host_identity_verified'], errors='coerce')
dfOttawa['instant_bookable'] = pd.to_numeric(dfOttawa['instant_bookable'], errors='coerce')
dfOttawa['price'] = dfOttawa['price'].str.replace(r'[\$,]', '', regex=True).astype(float)

In [199]:
# Extraemos el año de la última review y la del año donde inició el host de cada lugar
dfOttawa["last_review"]
dfOttawa["host_since"]
# Usar una expresión regular para extraer el año
dfOttawa['last_review'] = dfOttawa['last_review'].str.extract(r'(\d{4})')
dfOttawa['last_review'] = pd.to_numeric(dfOttawa['last_review'], errors='coerce')
dfOttawa['host_since'] = dfOttawa['host_since'].str.extract(r'(\d{4})')
dfOttawa['host_since'] = pd.to_numeric(dfOttawa['host_since'], errors='coerce')
# Agregamos una nueva columna
dfOttawa['host_years'] = dfOttawa["last_review"].max() - dfOttawa['host_since']

In [200]:
# Borramos las cualitativas
dfOttawa.drop(["description","neighborhood_overview","host_about","host_neighbourhood","name","neighbourhood","host_location","first_review","has_availability"], axis = 1, inplace = True)

# Borramos las cuantitativas
dfOttawa.drop(["scrape_id","minimum_nights","maximum_nights","minimum_minimum_nights","minimum_maximum_nights", "maximum_minimum_nights", "maximum_maximum_nights","availability_60", "availability_90", "calculated_host_listings_count_entire_homes", "calculated_host_listings_count_private_rooms", "calculated_host_listings_count_shared_rooms","last_review"], axis = 1, inplace = True)

In [201]:
# Dividimos por valores cuantitativos y cualitativos de nuevo pero con la base eliminada
cuantitativas = dfOttawa.select_dtypes(np.number)
cualitativas = dfOttawa.select_dtypes(include=['object'])

## Limpieza con los valores cualitativos

In [202]:
# Identificar valores cualitativos nulos
cualitativas.isnull().sum()

last_scraped                0
source                      0
host_name                   0
host_response_time        295
host_verifications          0
neighbourhood_cleansed      0
property_type               0
room_type                   0
bathrooms_text              3
amenities                   0
calendar_last_scraped       0
dtype: int64

In [203]:
cualiLimpieza = cualitativas.copy()

In [204]:
# Variable catégorica, será llenado con la moda dadas las categorías que tenemos y la distribución de los datos
moda = cualiLimpieza["host_response_time"].value_counts().index[0]
cualiLimpieza["host_response_time"] = cualiLimpieza["host_response_time"].fillna(moda)

In [205]:
# Variable que usaremos después por conteo de amenidades, también se realizará el conteo por la moda ya que son 3 registros y no afectará su distribución
moda1 = cualiLimpieza["bathrooms_text"].value_counts().index[0]
cualiLimpieza["bathrooms_text"] = cualiLimpieza["bathrooms_text"].fillna(moda)

In [206]:
# Corroboramos que no tengamos valores nulos
cualiLimpieza.isnull().sum().sum()

np.int64(0)

## Limpieza con los valores cuantitativos

In [207]:
# Generamos una copia para la limpieza
dfLimpiezaCuanti = cuantitativas.copy()

In [208]:
# Identificar valores cualitativos nulos
dfLimpiezaCuanti.isnull().sum()

host_id                             0
host_since                          0
host_response_rate                295
host_acceptance_rate              287
host_is_superhost                 113
host_listings_count                 0
host_total_listings_count           0
host_has_profile_pic                0
host_identity_verified              0
latitude                            0
longitude                           0
accommodates                        0
bathrooms                         210
bedrooms                           56
beds                              211
price                             209
minimum_nights_avg_ntm              0
maximum_nights_avg_ntm              0
availability_30                     0
availability_365                    0
number_of_reviews                   0
number_of_reviews_ltm               0
number_of_reviews_l30d              0
review_scores_rating              493
review_scores_accuracy            496
review_scores_cleanliness         496
review_scores_checkin             496
review_scores_communication       496
review_scores_location            496
review_scores_value               496
instant_bookable                    0
calculated_host_listings_count      0
reviews_per_month                 493
host_years                          0
dtype: int64

In [209]:
# Vemos un panorama general para las variables de "host_response_rate" y "host_acceptance_rate"
cuantitativas[["host_response_rate","host_acceptance_rate"]].head(5)
# En este caso, al trabajar con porcentajes (Que ya parten de un rango en específico), se decidió asignar reemplazo por promedio
dfLimpiezaCuanti["host_response_rate"] = dfLimpiezaCuanti["host_response_rate"].fillna(round(cuantitativas["host_response_rate"].mean(),1))
dfLimpiezaCuanti["host_acceptance_rate"] = dfLimpiezaCuanti["host_acceptance_rate"].fillna(round(cuantitativas["host_acceptance_rate"].mean(),1))

In [210]:
# Ahora vemos el caso de la columna "host_is_superhost"
cuantitativas["host_is_superhost"].value_counts()
# Reemplazaremos por un valor nuevo solo para mapear estos casos ya que esta columna es originalmente dicotómica
dfLimpiezaCuanti["host_is_superhost"] = dfLimpiezaCuanti["host_is_superhost"].fillna(2)

In [211]:
# Vemos un panorama general de variables tipo enteros comenzando con bathrooms, bedrooms y beds
cuantitativas[["bathrooms","bedrooms","beds"]].head(5)

   bathrooms  bedrooms  beds
0        1.0       1.0   3.0
1        1.0       2.0   2.0
2        1.0       1.0   1.0
3        1.0       5.0   4.0
4        1.0       2.0   2.0

In [212]:
"""Para valores como baños, habitaciones y camas, estas serán reemplazados por la mediana para no alterar la distribución de los datos,
tampoco tenemos un límite en establecido por lo que se seguirá con una distribución estandarizada"""

dfLimpiezaCuanti["bathrooms"] = dfLimpiezaCuanti["bathrooms"].fillna(int(round(cuantitativas["bathrooms"].median(), 0)))
dfLimpiezaCuanti["bedrooms"] = dfLimpiezaCuanti["bedrooms"].fillna(int(round(cuantitativas["bedrooms"].median(), 0)))
dfLimpiezaCuanti["beds"] = dfLimpiezaCuanti["beds"].fillna(int(round(cuantitativas["beds"].median(), 0)))

In [213]:
"""Ahora vemos la distribución del dataframe con aquellas columnas iniciando con 'review_scores', los valores son escala Likert"""

dfReviewScores = dfLimpiezaCuanti.loc[:, dfLimpiezaCuanti.columns.str.contains("review_scores")]
[dfReviewScores.min(), dfReviewScores.max()]

[review_scores_rating           1.0
 review_scores_accuracy         1.0
 review_scores_cleanliness      1.0
 review_scores_checkin          1.0
 review_scores_communication    1.0
 review_scores_location         1.0
 review_scores_value            1.0
 dtype: float64,
 review_scores_rating           5.0
 review_scores_accuracy         5.0
 review_scores_cleanliness      5.0
 review_scores_checkin          5.0
 review_scores_communication    5.0
 review_scores_location         5.0
 review_scores_value            5.0
 dtype: float64]

In [214]:
"""Limpiamos los valores de escala Likert con la media dado que sí hay un valor máximo definido"""

dfLimpiezaCuanti["review_scores_rating"] = dfLimpiezaCuanti["review_scores_rating"].fillna(round(cuantitativas["review_scores_rating"].mean(), 2))
dfLimpiezaCuanti["review_scores_accuracy"] = dfLimpiezaCuanti["review_scores_accuracy"].fillna(round(cuantitativas["review_scores_accuracy"].mean(), 2))
dfLimpiezaCuanti["review_scores_cleanliness"] = dfLimpiezaCuanti["review_scores_cleanliness"].fillna(round(cuantitativas["review_scores_cleanliness"].mean(), 2))
dfLimpiezaCuanti["review_scores_checkin"] = dfLimpiezaCuanti["review_scores_checkin"].fillna(round(cuantitativas["review_scores_checkin"].mean(), 2))
dfLimpiezaCuanti["review_scores_communication"] = dfLimpiezaCuanti["review_scores_communication"].fillna(round(cuantitativas["review_scores_communication"].mean(), 2))
dfLimpiezaCuanti["review_scores_location"] = dfLimpiezaCuanti["review_scores_location"].fillna(round(cuantitativas["review_scores_location"].mean(), 2))
dfLimpiezaCuanti["review_scores_value"] = dfLimpiezaCuanti["review_scores_value"].fillna(round(cuantitativas["review_scores_value"].mean(), 2))

In [215]:
# Al ser escala de Likert, nos interesa que estén redondeados a valor entero

dfLimpiezaCuanti["review_scores_rating"] = dfLimpiezaCuanti["review_scores_rating"].round()
dfLimpiezaCuanti["review_scores_accuracy"] = dfLimpiezaCuanti["review_scores_accuracy"].round()
dfLimpiezaCuanti["review_scores_cleanliness"] = dfLimpiezaCuanti["review_scores_cleanliness"].round()
dfLimpiezaCuanti["review_scores_checkin"] = dfLimpiezaCuanti["review_scores_checkin"].round()
dfLimpiezaCuanti["review_scores_communication"] = dfLimpiezaCuanti["review_scores_communication"].round()
dfLimpiezaCuanti["review_scores_location"] = dfLimpiezaCuanti["review_scores_location"].round()
dfLimpiezaCuanti["review_scores_value"] = dfLimpiezaCuanti["review_scores_value"].round()

In [216]:
# Comprobación del cambio

dfReviewScores = dfLimpiezaCuanti.loc[:, dfLimpiezaCuanti.columns.str.contains("review_scores")]
dfReviewScores.value_counts()

review_scores_rating  review_scores_accuracy  review_scores_cleanliness  review_scores_checkin  review_scores_communication  review_scores_location  review_scores_value
5.0                   5.0                     5.0                        5.0                    5.0                          5.0                     5.0                    2296
                                              4.0                        5.0                    5.0                          5.0                     5.0                      69
                                              5.0                        5.0                    5.0                          5.0                     4.0                      62
                                                                                                                             4.0                     5.0                      53
4.0                   4.0                     4.0                        5.0                    5.0                          4.0                     4.0                      19
                                                                                                                                                                            ...
5.0                   5.0                     5.0                        4.0                    4.0                          4.0                     5.0                       1
                                                                         5.0                    4.0                          4.0                     5.0                       1
                                                                                                3.0                          1.0                     1.0                       1
                                                                                                5.0                          3.0                     5.0                       1
                                                                                                                             5.0                     3.0                       1
Name: count, Length: 135, dtype: int64

In [217]:
# Reviews per month no tiene un valor máximo asignado ni es una columna estandarizada, debido a esto, se decidió sustituir con la mediana
dfLimpiezaCuanti["reviews_per_month"] = dfLimpiezaCuanti["reviews_per_month"].fillna(round(cuantitativas["reviews_per_month"].median(), 2))

In [218]:
"""Finalmente para la columna de precio, utilizaremos la mediana ya que no queremos afectar la distribución de los datos y,
además al ser pocos registros en proporción a la base, no hay problema en utilizar este método"""
dfLimpiezaCuanti["price"] = dfLimpiezaCuanti["price"].fillna(round(cuantitativas["price"].median(), 0))

In [219]:
# Corroboramos que no tengamos valores nulos
dfLimpiezaCuanti.isnull().sum().sum()

np.int64(0)

## Categorización de valores

In [220]:
# Unimos ambas limpiezas (Valores cuantitativos y cualitativos limpios)
dfOttawaLimpio = pd.concat([cualiLimpieza, dfLimpiezaCuanti], axis=1)

In [221]:
# Comprobamos que sí estén todos los datos en ambas bases, tanto la inicial como la que tuvo un proceso de limpieza
dfOttawa.info()
dfOttawaLimpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2862 entries, 0 to 2861
Data columns (total 45 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   last_scraped                    2862 non-null   object
 1   source                          2862 non-null   object
 2   host_id                         2862 non-null   int64
 3   host_name                       2862 non-null   object
 4   host_since                      2862 non-null   int64
 5   host_response_time              2567 non-null   object
 6   host_response_rate              2567 non-null   float64
 7   host_acceptance_rate            2575 non-null   float64
 8   host_is_superhost               2749 non-null   float64
 9   host_listings_count             2862 non-null   int64
 10  host_total_listings_count       2862 non-null   int64
 11  host_verifications              2862 non-null   object
 12  host_has_profile_pic            2862 non-null   int64
 13  host_identity_verified          2862 non-null   int64
 14  neighbourhood_cleansed          2862 non-null   object
 15  latitude                        2862 non-null   float64
 16  longitude                       2862 non-null   float64
 17  property_type                   2862 non-null   object
 18  room_type                       2862 non-null   object
 19  accommodates                    2862 non-null   int64
 20  bathrooms                       2652 non-null   float64
 21  bathrooms_text                  2859 non-null   object
 22  bedrooms                        2806 non-null   float64
 23  beds                            2651 non-null   float64
 24  amenities                       2862 non-null   object
 25  price                           2653 non-null   float64
 26  minimum_nights_avg_ntm          2862 non-null   float64
 27  maximum_nights_avg_ntm          2862 non-null   float64
 28  availability_30                 2862 non-null   int64
 29  availability_365                2862 non-null   int64
 30  calendar_last_scraped           2862 non-null   object
 31  number_of_reviews               2862 non-null   int64
 32  number_of_reviews_ltm           2862 non-null   int64
 33  number_of_reviews_l30d          2862 non-null   int64
 34  review_scores_rating            2369 non-null   float64
 35  review_scores_accuracy          2366 non-null   float64
 36  review_scores_cleanliness       2366 non-null   float64
 37  review_scores_checkin           2366 non-null   float64
 38  review_scores_communication     2366 non-null   float64
 39  review_scores_location          2366 non-null   float64
 40  review_scores_value             2366 non-null   float64
 41  instant_bookable                2862 non-null   int64
 42  calculated_host_listings_count  2862 non-null   int64
 43  reviews_per_month               2369 non-null   float64
 44  host_years                      2862 non-null   float64
dtypes: float64(20), int64(14), object(11)
memory usage: 1006.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2862 entries, 0 to 2861
Data columns (total 45 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   last_scraped                    2862 non-null   object
 1   source                          2862 non-null   object
 2   host_name                       2862 non-null   object
 3   host_response_time              2862 non-null   object
 4   host_verifications              2862 non-null   object
 5   neighbourhood_cleansed          2862 non-null   object
 6   property_type                   2862 non-null   object
 7   room_type                       2862 non-null   object
 8   bathrooms_text                  2862 non-null   object
 9   amenities                       2862 non-null   object
 10  calendar_last_scraped           2862 non-null   object
 11  host_id                         2862 non-null   int64
 12  host_since                      2862 non-null   int64
 13  host_response_rate              2862 non-null   float64
 14  host_acceptance_rate            2862 non-null   float64
 15  host_is_superhost               2862 non-null   float64
 16  host_listings_count             2862 non-null   int64
 17  host_total_listings_count       2862 non-null   int64
 18  host_has_profile_pic            2862 non-null   int64
 19  host_identity_verified          2862 non-null   int64
 20  latitude                        2862 non-null   float64
 21  longitude                       2862 non-null   float64
 22  accommodates                    2862 non-null   int64
 23  bathrooms                       2862 non-null   float64
 24  bedrooms                        2862 non-null   float64
 25  beds                            2862 non-null   float64
 26  price                           2862 non-null   float64
 27  minimum_nights_avg_ntm          2862 non-null   float64
 28  maximum_nights_avg_ntm          2862 non-null   float64
 29  availability_30                 2862 non-null   int64
 30  availability_365                2862 non-null   int64
 31  number_of_reviews               2862 non-null   int64
 32  number_of_reviews_ltm           2862 non-null   int64
 33  number_of_reviews_l30d          2862 non-null   int64
 34  review_scores_rating            2862 non-null   float64
 35  review_scores_accuracy          2862 non-null   float64
 36  review_scores_cleanliness       2862 non-null   float64
 37  review_scores_checkin           2862 non-null   float64
 38  review_scores_communication     2862 non-null   float64
 39  review_scores_location          2862 non-null   float64
 40  review_scores_value             2862 non-null   float64
 41  instant_bookable                2862 non-null   int64
 42  calculated_host_listings_count  2862 non-null   int64
 43  reviews_per_month               2862 non-null   float64
 44  host_years                      2862 non-null   float64
dtypes: float64(20), int64(14), object(11)
memory usage: 1006.3+ KB

In [222]:
# Asignamos categorías a las columnas de tipo texto con valores numéricos usando la libreria de sklearn
labels = LabelEncoder()
# Convertir la columna de texto a valores numéricos (Categorizar con números)
dfOttawaLimpio['room_type_num'] = labels.fit_transform(dfOttawaLimpio['room_type'])
dfOttawaLimpio['neighbourhood_cleansed_num'] = labels.fit_transform(dfOttawaLimpio['neighbourhood_cleansed'])
dfOttawaLimpio['host_response_time_num'] = labels.fit_transform(dfOttawaLimpio['host_response_time'])

In [223]:
# Obtenemos categorías para bathrooms_text:
dfOttawaLimpio['bathroom_text_clean'] = dfOttawaLimpio['bathrooms_text'].str.replace(r'^\d*\.?\d*\s?', '', regex=True).str.strip()
dfOttawaLimpio['bathroom_text_clean'] = dfOttawaLimpio['bathroom_text_clean'].str.replace("baths","bath")
dfOttawaLimpio['bathroom_text_clean'] = dfOttawaLimpio['bathroom_text_clean'].str.replace("shared baths","shared bath")
dfOttawaLimpio['bathroom_text_clean'].value_counts()
# Las volvemos numéricas:
dfOttawaLimpio['bathroom_text_num'] = labels.fit_transform(dfOttawaLimpio['bathroom_text_clean'])
dfOttawaLimpio['bathroom_text_num'].value_counts()

bathroom_text_num
3    2128
5     484
4     241
6       3
0       3
1       2
2       1
Name: count, dtype: int64

In [224]:
# Conteo para la variable "amenities" y "host_verifications"
dfOttawaLimpio['amenities_num'] = dfOttawaLimpio['amenities'].apply(ast.literal_eval)
dfOttawaLimpio["host_verifications_num"] = dfOttawaLimpio['host_verifications'].apply(ast.literal_eval)
# Crear una nueva columna que cuenta los elementos de la lista
dfOttawaLimpio['amenities_num'] = dfOttawaLimpio['amenities_num'].apply(len)
dfOttawaLimpio['host_verifications_num'] = dfOttawaLimpio['host_verifications_num'].apply(len)

In [225]:
#Comprobación rápida de "amenities"
dfWhere = dfOttawaLimpio[["amenities","amenities_num"]]
dfWhere
dfWhere[dfWhere["amenities_num"] == 2]
dfWhere[dfWhere["amenities_num"] == 0]

     amenities  amenities_num
185         []              0
1341        []              0
1382        []              0
2469        []              0

In [226]:
#Comprobación rápida de "host_verifications"
dfWhere1 = dfOttawaLimpio[["host_verifications","host_verifications_num"]]
dfWhere1
dfWhere1[dfWhere1["host_verifications_num"] == 2]
dfWhere1[dfWhere1["host_verifications_num"] == 0]

     host_verifications  host_verifications_num
824                  []                       0
2036                 []                       0
2233                 []                       0

In [227]:
#Base final
dfOttawaLimpio

,last_scraped,source,host_name,host_response_time,host_verifications,neighbourhood_cleansed,property_type,room_type,bathrooms_text,amenities,...,calculated_host_listings_count,reviews_per_month,host_years,room_type_num,neighbourhood_cleansed_num,host_response_time_num,bathroom_text_clean,bathroom_text_num,amenities_num,host_verifications_num
0,2024-06-21,city scrape,Glenn,within an hour,"['email', 'phone']",Kitchissippi,Entire rental unit,Entire home/apt,1 bath,"[""Kitchen"", ""Shampoo"", ""Coffee maker"", ""Smoke ...",...,1,0.65,13.0,0,12,3,bath,3,28,2
1,2024-06-21,city scrape,Daniel,within a day,"['email', 'phone']",Rideau-Goulbourn,Entire home,Entire home/apt,1 bath,"[""Extra pillows and blankets"", ""Kitchen"", ""Sha...",...,1,0.04,13.0,0,16,1,bath,3,61,2
2,2024-06-21,city scrape,Ela,within an hour,"['email', 'phone']",Capital,Private room in home,Private room,1 private bath,"[""Free washer \u2013 In building"", ""Extra pill...",...,1,0.12,12.0,1,4,3,private bath,4,49,2
3,2024-06-21,city scrape,William,within an hour,['phone'],Gloucester-South Nepean,Entire home,Entire home/apt,1 bath,"[""Kitchen"", ""Shampoo"", ""Host greets you"", ""Smo...",...,1,0.57,12.0,0,7,3,bath,3,27,1
4,2024-06-21,city scrape,Greg And Valerie,within an hour,"['email', 'phone', 'work_email']",Kitchissippi,Entire home,Entire home/apt,1 bath,"[""Extra pillows and blankets"", ""Self check-in""...",...,6,0.09,12.0,0,12,3,bath,3,45,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2857,2024-06-21,city scrape,Vivek,within an hour,"['email', 'phone']",Gloucester-South Nepean,Private room in home,Private room,1 private bath,"[""Extra pillows and blankets"", ""Shampoo"", ""Hos...",...,3,1.16,8.0,1,7,3,private bath,4,35,2
2858,2024-06-21,city scrape,Tatiana,within an hour,"['email', 'phone']",Rideau-Vanier,Private room in rental unit,Private room,1 bath,"[""Washer"", ""Carbon monoxide alarm"", ""Kitchen"",...",...,1,1.16,4.0,1,18,3,bath,3,9,2
2859,2024-06-21,city scrape,Genevieve,within an hour,"['email', 'phone', 'work_email']",Osgoode,Entire home,Entire home/apt,3 baths,"[""Extra pillows and blankets"", ""Self check-in""...",...,63,1.16,8.0,0,15,3,bath,3,57,3
2860,2024-06-21,city scrape,Shannon,within an hour,"['email', 'phone', 'work_email']",Kitchissippi,Entire rental unit,Entire home/apt,1 bath,"[""Free parking on premises"", ""Washer"", ""Air co...",...,1,1.16,10.0,0,12,3,bath,3,4,3
2861,2024-06-21,city scrape,Mitham,within an hour,['phone'],Osgoode,Entire home,Entire home/apt,4 baths,"[""Free parking on premises"", ""Washer"", ""Carbon...",...,1,1.16,5.0,0,15,3,bath,3,15,1

In [228]:
# El precio está en moneda local, se decidió estandarizar a peso mexicano para que todos tengamos la misma información

pesoMex = 14.5680
dfOttawaLimpio["priceMex"] = dfOttawaLimpio["price"] * pesoMex

In [229]:
# Redondeamos a dos decimales
dfOttawaLimpio["priceMex"] = np.round(dfOttawaLimpio["priceMex"],2)

In [230]:
# Corroboramos la conversión

dfOttawaLimpio[["priceMex","price"]].min()

priceMex    320.5
price        22.0
dtype: float64

## Categorización de la columna precio (Estandarizada a Mx)

In [231]:
#Calculamos el número total de la población "n"
n = len(dfOttawaLimpio['priceMex'])
n
# Límites
Max = dfOttawaLimpio["priceMex"].max()
Min = dfOttawaLimpio["priceMex"].min()
Limites = [Min, Max]
Limites

[np.float64(320.5), np.float64(72840.0)]

In [232]:
# Calculamos el rango R
R = Max - Min
R

np.float64(72519.5)

In [233]:
# Regla de Sturges: Calcular el número de Intervalos de Clase "ni"
ni = 1 + 3.32*np.log10(n)
ni = int(ni)
ni
#Según la regla, no debe sobrepasar las 12 categorias (Se tomarán 12)

12

In [234]:
# Calculamos el ancho del intervalo "i"
i = R/ni
i

np.float64(6043.291666666667)

In [235]:
# Categorización de variables
intervalos = np.linspace(Min, Max, ni)
np.round(intervalos, 2)

array([  320.5 ,  6913.18, 13505.86, 20098.55, 26691.23, 33283.91,
       39876.59, 46469.27, 53061.95, 59654.64, 66247.32, 72840.  ])

In [236]:
# Definir las categorías
categorias = ['Básico (320.5 - 6,913.18)', 'Muy Económico (6,913.19 - 13,505.86)', 'Económico (13,505.87 - 20,098.55)', 'Estándar (20,098.56 - 26,691.23)',
              'Costo Moderado (26,691.24 - 33,283.91)', 'Costo Elevado (33,283.92 - 39,876.59)', 'Premium (39,876.60 - 46,469.27)', 
              'De Lujo (46469.28 - 53,061.95)', 'Elite (53,061.96 - 59,654.64)', 'Exclusivo (59,654.65 - 66,247.32)', 'Top de Mercado (66,247.33 - 72,840)']

# Se asignan en una nueva columna
dfOttawaLimpio['priceMexCategory'] = pd.cut(x = dfOttawaLimpio['priceMex'], bins = intervalos, labels = categorias, include_lowest=True)
dfOttawaLimpio['priceMexCategory']

0                  Básico (320.5 - 6,913.18)
1                  Básico (320.5 - 6,913.18)
2                  Básico (320.5 - 6,913.18)
3                  Básico (320.5 - 6,913.18)
4                  Básico (320.5 - 6,913.18)
                        ...
2857               Básico (320.5 - 6,913.18)
2858               Básico (320.5 - 6,913.18)
2859    Muy Económico (6,913.19 - 13,505.86)
2860               Básico (320.5 - 6,913.18)
2861    Muy Económico (6,913.19 - 13,505.86)
Name: priceMexCategory, Length: 2862, dtype: category
Categories (11, object): ['Básico (320.5 - 6,913.18)' < 'Muy Económico (6,913.19 - 13,505.86)' < 'Económico (13,505.87 - 20,098.55)' < 'Estándar (20,098.56 - 26,691.23)' ... 'De Lujo (46469.28 - 53,061.95)' < 'Elite (53,061.96 - 59,654.64)' < 'Exclusivo (59,654.65 - 66,247.32)' < 'Top de Mercado (66,247.33 - 72,840)']

In [237]:
# Corroboramos:

dfOttawaLimpio[['priceMexCategory', "priceMex"]]

                          priceMexCategory  priceMex
0                Básico (320.5 - 6,913.18)   2549.40
1                Básico (320.5 - 6,913.18)   2913.60
2                Básico (320.5 - 6,913.18)   1078.03
3                Básico (320.5 - 6,913.18)    961.49
4                Básico (320.5 - 6,913.18)   1325.69
...                                    ...       ...
2857             Básico (320.5 - 6,913.18)    874.08
2858             Básico (320.5 - 6,913.18)    509.88
2859  Muy Económico (6,913.19 - 13,505.86)   7473.38
2860             Básico (320.5 - 6,913.18)   1165.44
2861  Muy Económico (6,913.19 - 13,505.86)   6992.64

[2862 rows x 2 columns]

In [238]:
# La categorización también la realizamos en formato numérico
dfOttawaLimpio['priceMexCategory_num'] = labels.fit_transform(dfOttawaLimpio['priceMexCategory'])

In [239]:
dfOttawaLimpio['priceMexCategory_num'].value_counts()

priceMexCategory_num
0    2790
3      64
1       4
4       2
2       2
Name: count, dtype: int64

In [240]:
# Se corrobora una última vez

dfOttawaLimpio.isnull().sum().sum()

np.int64(0)

In [241]:
dfOttawaLimpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2862 entries, 0 to 2861
Data columns (total 55 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   last_scraped                    2862 non-null   object
 1   source                          2862 non-null   object
 2   host_name                       2862 non-null   object
 3   host_response_time              2862 non-null   object
 4   host_verifications              2862 non-null   object
 5   neighbourhood_cleansed          2862 non-null   object
 6   property_type                   2862 non-null   object
 7   room_type                       2862 non-null   object
 8   bathrooms_text                  2862 non-null   object
 9   amenities                       2862 non-null   object
 10  calendar_last_scraped           2862 non-null   object
 11  host_id                         2862 non-null   int64
 12  host_since                      2862 non-null   int64
 13  host_response_rate              2862 non-null   float64
 14  host_acceptance_rate            2862 non-null   float64
 15  host_is_superhost               2862 non-null   float64
 16  host_listings_count             2862 non-null   int64
 17  host_total_listings_count       2862 non-null   int64
 18  host_has_profile_pic            2862 non-null   int64
 19  host_identity_verified          2862 non-null   int64
 20  latitude                        2862 non-null   float64
 21  longitude                       2862 non-null   float64
 22  accommodates                    2862 non-null   int64
 23  bathrooms                       2862 non-null   float64
 24  bedrooms                        2862 non-null   float64
 25  beds                            2862 non-null   float64
 26  price                           2862 non-null   float64
 27  minimum_nights_avg_ntm          2862 non-null   float64
 28  maximum_nights_avg_ntm          2862 non-null   float64
 29  availability_30                 2862 non-null   int64
 30  availability_365                2862 non-null   int64
 31  number_of_reviews               2862 non-null   int64
 32  number_of_reviews_ltm           2862 non-null   int64
 33  number_of_reviews_l30d          2862 non-null   int64
 34  review_scores_rating            2862 non-null   float64
 35  review_scores_accuracy          2862 non-null   float64
 36  review_scores_cleanliness       2862 non-null   float64
 37  review_scores_checkin           2862 non-null   float64
 38  review_scores_communication     2862 non-null   float64
 39  review_scores_location          2862 non-null   float64
 40  review_scores_value             2862 non-null   float64
 41  instant_bookable                2862 non-null   int64
 42  calculated_host_listings_count  2862 non-null   int64
 43  reviews_per_month               2862 non-null   float64
 44  host_years                      2862 non-null   float64
 45  room_type_num                   2862 non-null   int64
 46  neighbourhood_cleansed_num      2862 non-null   int64
 47  host_response_time_num          2862 non-null   int64
 48  bathroom_text_clean             2862 non-null   object
 49  bathroom_text_num               2862 non-null   int64
 50  amenities_num                   2862 non-null   int64
 51  host_verifications_num          2862 non-null   int64
 52  priceMex                        2862 non-null   float64
 53  priceMexCategory                2862 non-null   category
 54  priceMexCategory_num            2862 non-null   int64
dtypes: category(1), float64(21), int64(21), object(12)
memory usage: 1.2+ MB

In [242]:
# Convertir Dataframe a CSV
dfOttawaLimpio.to_excel("OttawaLimpio.xlsx")